# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

luck_adj_rcpp <- function(prevsurv, cursurv, luck, condq = TRUE) {
    .Call(`_WARDEN_luck_adj_rcpp`, prevsurv, cursurv, luck, condq)
}

qcond_exp_cpp <- function(rnd, rate) {
    .Call(`_WARDEN_qcond_exp_cpp`, rnd, rate)
}

qcond_weibull_cpp <- function(rnd, shape, scale, lower_bound = as.numeric( c(0.0))) {
    .Call(`_WARDEN_qcond_weibull_cpp`, rnd, shape, scale, lower_bound)
}

qcond_weibullPH_cpp <- function(rnd, shape, scale, lower_bound = as.numeric( c(0.0))) {
    .Call(`_WARDEN_qcond_weibullPH_cpp`, rnd, shape, scale, lower_bound)
}

qcond_llogis_cpp <- function(rnd, shape, scale, lower_bound = as.numeric( c(0.0))) {
    .Call(`_WARDEN_qcond_llogis_cpp`, rnd, shape, scale, lower_bound)
}

qcond_gompertz_cpp <- function(rnd, shape, rate, lower_bound = as.numeric( c(0.0))) {
    .Call(`_WARDEN_qcond_gompertz_cpp`, rnd, shape, rate, lower_bound)
}

qcond_lnorm_cpp <- function(rnd, meanlog, sdlog, lower_bound, s_obs) {
    .Call(`_WARDEN_qcond_lnorm_cpp`, rnd, meanlog, sdlog, lower_bound, s_obs)
}

qcond_norm_cpp <- function(rnd, mean, sd, lower_bound, s_obs) {
    .Call(`_WARDEN_qcond_norm_cpp`, rnd, mean, sd, lower_bound, s_obs)
}

qcond_gamma_cpp <- function(rnd, shape, rate, lower_bound, s_obs) {
    .Call(`_WARDEN_qcond_gamma_cpp`, rnd, shape, rate, lower_bound, s_obs)
}

qtimecov_cpp <- function(luck, a_fun, b_fun = NULL, dist = "exp", dt = 0.1, max_time = 100, start_time = 0) {
    .Call(`_WARDEN_qtimecov_cpp`, luck, a_fun, b_fun, dist, dt, max_time, start_time)
}

disc_cycle_rcpp <- function(lcldr, lclprvtime, cyclelength, lclcurtime, lclval, starttime, max_cycles = NULL) {
    .Call(`_WARDEN_disc_cycle_rcpp`, lcldr, lclprvtime, cyclelength, lclcurtime, lclval, starttime, max_cycles)
}

disc_instant_rcpp <- function(lcldr, lclcurtime, lclval) {
    .Call(`_WARDEN_disc_instant_rcpp`, lcldr, lclcurtime, lclval)
}

disc_ongoing_rcpp <- function(lcldr, lclprvtime, lclcurtime, lclval) {
    .Call(`_WARDEN_disc_ongoing_rcpp`, lcldr, lclprvtime, lclcurtime, lclval)
}

